[package]
name = "puzzle-path-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
puzzle-base = { version = "0.1.0", path = "../base" }
puzzle-base-macros = { version = "0.1.0", path = "../base_macros" }
puzzle-formats = { version = "0.1.0", path = "../puzzfmt_lib" }
