[package]
name = "puzzle-path-tool-c"
version = "0.1.0"
edition = "2024"

[dependencies]
puzzle-path-tool = { version = "0.1.0", path = "../puzzpt_lib" }

[build-dependencies]
puzzle-base-build = { version = "0.1.0", path = "../base_build" }
