[package]
name = "puzzle-base"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
