[package]
name = "puzzle-core-build"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
